### ISSUE TITLE
Cannot access the web interface from IP only from localhost

### ISSUE THREAD

**Issue by L0G5** [graniet/operative-framework-HD#1]
I am trying to access the web interface on 192.168.60.140 & port:5000 but it seems that i cannot.
I have tried to disable debug mode but that was not possible. More specifically i tried the following but nothing seems to deactivate the debug mode, assuming that is the issue i cant access it through  192.168.60.140:5000. Any thoughts on what could be the issue? Thank you.

app.run(debug=False .....)
host="0.0.0.0", port="5000"
FLASK_DEBUG=False
DEBUG=False

**Comment by graniet** [comment]
Hello,

Thanks for using Operative Framework HD,
You start operative with **bin/opf_server.py** ? or with global command **opf_server**?

if you replace in **framework/app.py**

`app.run(debug=True, port=config.BACKEND_PORT)`

by

`app.run(debug=True, host='0.0.0.0', port=config.BACKEND_PORT)`

and your start sudo python framework/app.py this is work?

Thanks.

**Comment by L0G5** [comment]
Thank you for building it. 
I use the global command **sudo opf_server**
I have already tried that specified change but unfortunately it did not work. 
I can confirm that it starts now using **sudo python framework/app.py** but still does not work using global or **sudo python bin/opf_server.py** directly.

**Sudo opf_client** works but without any functional interaction on webUI. (Login does not work)
Further i received the following warning when i run the client

Compiled with warnings.
./src/components/Projects/index.jsx
  Line 218:  Expected '===' and instead saw '=='  eqeqeq
./src/components/Account/index.jsx
  Line 2:   'EngineUsers' is defined but never used               no-unused-vars
  Line 3:   'Tree' is defined but never used                      no-unused-vars
  Line 22:  'containerStyles' is assigned a value but never used  no-unused-vars

**Comment by graniet** [comment]
Thanks you for your response,

if you use **global command** you need update framework code in **~/.operative_framework/** folder

You can check and write status here?

PS: The warning  is just no used variable no worrie with your problem :-)

**Comment by graniet** [comment]
i will make code update this day for warnings and for add host='0.0.0.0' line :-)

**Comment by graniet** [comment]
@L0G5 I have update a README.md with client configuration, sorry for forgetting lol

**Comment by L0G5** [comment]
Yes indeed after the change, everything works from **global command**.
Console commands also work (**sudo opf_console, run_clien, run_server**)

However i cannot Log in the WebUI.
Accounts were created successfully in previous steps but there is no interaction in WebUI. 
I will assume this is a different problem, right?

> i will make code update this day for warnings and for add host='0.0.0.0' line :-)
Thank you for your quick response and help.

**Comment by graniet** [comment]
@LOGS

for the login i have resolve issue on new push,
i have replace you can do it manually if you want sorry for forgetting :

**file:** /client/src/components/Account/index.jsx

`"127.0.0.1:5000/auth/user/login"`

by 

`SERVER_ADDR +"/auth/user/login"`

You can check and write status here?

Thanks :)

**Comment by L0G5** [comment]
Thank you for your patience. I am working on it in my job thats why i am delaying.
Well i did all the changes and i did not get funtion on WebUI, so i tried by deleting it and reinstall it from scratch.
Now everything works but when i run the client (**sudo opf_client**), it gives me this error, which i am sure i am missing something here...

```
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start" "--prefix" "/home/****/.operative_framework/client/"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/****/.operative_framework/client/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/****/.operative_framework/client/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/****/.operative_framework/client/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/****/operative-framework-HD/npm-debug.log
```

**Comment by graniet** [comment]
@L0G5 

You have start **install.sh** with new version the package.json it's on /home/****/.operative_framework/?

if you start client with **npm install** && **npm start** on **client folder** this is work?

**Comment by L0G5** [comment]
@graniet 

I have made a clean install from start on a new untouched system.
I can confirm that the previous issue is completely resolved without config changes.
However the problem with WebUI interaction still persists.
Any thoughts on that?

**Comment by graniet** [comment]
@L0G5 

Thanks for you response :)

Humm, you have update config file of client with your local ip address?

**Comment by graniet** [comment]
@L0G5 

Thanks for you return,

You can't login it's a error?

If you start manually **sudo python framework/app.py** and **cd client && npm install && npm start** in another shell, you have error when you log-in?

You updated config file in project folder or **globally** ~/.operative_framework/client/... ? 

don't forget if you use **global command** you need update your config in **~/.operative_framework/** not in cloned repository

**Comment by L0G5** [comment]
@graniet 

Yes I also did change it in **~/.operative_framework/** for **global command**.
The only way i was able to login was by using **npm install && npm start** or just **npm start** in another shell or the same shell.
Tested **opf_console** and it produces the same problem.

**Comment by graniet** [comment]
Ok if i understand, always it's ok when you start with npm install && npm start ?

but no with global binary ? and if you start with sudo python bin/opf_client.py in clone folder it's ok?

thanks you for your return ! 👍

**Comment by L0G5** [comment]
@graniet 

Yes **npm install && npm start** works perfectly.
Also **sudo python bin/opf_client.py** works.
Globally it does not work.

**Comment by graniet** [comment]
@L0G5 

Ok perfect !

No worrie, i hope you like this software.

Thanks for your issue !
