### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by the-Blue-Falcon** [graniet/operative-framework-HD#2]
Hi there,

Thanks for this big work. I really want to use your framework but I am getting an error something like this after running framework/app.py. Everything went fine till this error. :(
```
Traceback (most recent call last):
  File "framework/app.py", line 189, in <module>
    app.run(debug=True, host='0.0.0.0', port=config.BACKEND_PORT)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required
```
I have updated the client configuration in the `/client/src/components/Config/index.jsx` to my local IP. All instructions followed. The mongodb service is running. I have done a local individual manual install. Running this on Python2 Kali 2018.2. Can you help me?

Regards

**Comment by graniet** [comment]
Hello @the-Blue-Falcon ,

Thanks for using Operative Framework.

You can change this (framework/config.py):

BACKEND_PORT = "5000" **=>** BACKEND_PORT = 5000
FRONTEND_PORT = "3000" **=>** FRONTEND_PORT = 3000

This is work?

**Comment by the-Blue-Falcon** [comment]
Yes it works like a charm! Thank you for fixing it. However I have another error now. When I run `./opf_server.py` and then `./opf_client`, it gives me something like this:
```
[2018-09-15 04:44:17] INFORM Welcome to Operative Framework clientHD 1.0
[2018-09-15 04:44:17] ERROR Please run backend sudo python bin/opf_server.py
```
opf_server.py is already running in background in another terminal, I don't know why is this happening?

Can you help me? :(

**Comment by the-Blue-Falcon** [comment]
Nah, I guess it was some OSError or something like that. I decided to do a new clone and everything worked fine asf. 💯 It opened up but I was having a small bug. Every module I work is working more or less fine but whenver I go the graphical view, the graph box always says, `Please wait...`. Even after using a lot of modules in same website, It still says that. :(

Btw, great tool and very versatile.

**Comment by graniet** [comment]
@the-Blue-Falcon Thanks for you comment ! i hope this tool helps you in your investigation.

i update version soon with new modules !
